version: "3.5"
services:
  geth:
    build:
      context: op-geth
      args:
        UPSTREAM_VERSION: v1.101105.3
    volumes:
      - "data:/data"
    restart: unless-stopped
    environment:
      - EXTRA_FLAGS
      - P2P_PORT=33141
      - SYNCMODE=snap
      - "HISTORICAL_RPC_URL=http://op-l2geth.dappnode:8545"
      - "SEQUENCER_HTTP_URL=https://bedrock-beta-1-sequencer.optimism.io"
      - ENABLE_HISTORICAL_RPC=true
      - GENESIS_MODE=PresyncedDatabase
    image: "geth.op-geth.dnp.dappnode.eth:0.1.0"
volumes:
  data: {}
