version: "3.5"
services:
  geth:
    build:
      context: op-geth
      args:
        UPSTREAM_VERSION: latest
    volumes:
      - "data:/data"
    ports:
      - "33141:33141/tcp"
      - "33141:33141/udp"
    restart: unless-stopped
    environment:
      - EXTRA_FLAGS
      - P2P_PORT=33141
      - SYNCMODE=snap
    image: "geth.lukso-geth.dnp.dappnode.eth:0.1.0"
volumes:
  lukso: {}
